### ISSUE TITLE
Spider base atende_v2 dando erro com o município de Araucaria-PR

### ISSUE THREAD

**Issue by trevineju** [okfn-brasil/querido-diario#1269]
Conforme validado por @marcospscruz na PR #1167, a spider base está funcional para diversos casos (e também para os casos em produção). Porém para Araucaria dá o seguinte erro:

> 2024-06-16 13:11:02 [scrapy.core.scraper] ERROR: Spider error processing <GET https://araucaria.atende.net/diariooficial/edicao/pagina/atende.php?rot=54015&aca=101&ajax=t&processo=loadPluginDiarioOficial&parametro=%7B%22codigoPlugin%22%3A1%2C%22filtroPlugin%22%3A%7B%22pagina%22%3A%221%22%7D%7D> (referer: None)
Traceback (most recent call last):
...
  File "/home/marcos/Documentos/querido-diario/data_collection/gazette/spiders/base/atende_v2.py", line 54, in parse
    download_url = item.css("button::attr(data-link)")[-1].get()
  File "/home/marcos/Documentos/querido-diario/venv/lib/python3.10/site-packages/parsel/selector.py", line 143, in __getitem__
    o = super().__getitem__(pos)
IndexError: list index out of range

O log dessa coleta está em https://github.com/okfn-brasil/querido-diario/pull/1167#issuecomment-2171765082

É necessário verificar a situação, corrigindo a spider base caso necessário, tomando cuidado também de verificar o impacto em outros spiders que usam a base.

**Comment by sheory** [comment]
Investigando essa issue
