### ISSUE TITLE
Error installing packages

### ISSUE THREAD

**Issue by gsusin** [okfn-brasil/querido-diario#408]
I'm following the instructions to install the development environment and I got this error:
```
(.venv) susin@bemtevi:~/code/querido-diario> pip install -r data_collection/requirements.txt
Collecting appdirs==1.4.4
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting attrs==20.2.0
  Using cached attrs-20.2.0-py2.py3-none-any.whl (48 kB)
Collecting automat==20.2.0
  Using cached Automat-20.2.0-py2.py3-none-any.whl (31 kB)
Collecting awscli==1.18.167
  Using cached awscli-1.18.167-py2.py3-none-any.whl (3.4 MB)
Collecting black==20.8b1
  Using cached black-20.8b1.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting boto3==1.16.0
  Using cached boto3-1.16.0-py2.py3-none-any.whl (129 kB)
Collecting botocore==1.19.7
  Using cached botocore-1.19.7-py2.py3-none-any.whl (6.7 MB)
Collecting cffi==1.14.3
  Using cached cffi-1.14.3-cp36-cp36m-manylinux1_x86_64.whl (400 kB)
Collecting cfgv==3.2.0
  Using cached cfgv-3.2.0-py2.py3-none-any.whl (7.3 kB)
Collecting chompjs==1.0.16
  Using cached chompjs-1.0.16.tar.gz (7.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/susin/code/querido-diario/.venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nvrytec4/chompjs_490795f88bd44b3eaefdf546297410b1/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nvrytec4/chompjs_490795f88bd44b3eaefdf546297410b1/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-s8sy6wmi
         cwd: /tmp/pip-install-nvrytec4/chompjs_490795f88bd44b3eaefdf546297410b1/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/susin/code/querido-diario/.venv/lib64/python3.6/site-packages/setuptools/__init__.py", line 15, in <module>
        from six import PY3, string_types
    ModuleNotFoundError: No module named 'six'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
If I install that module with `pip install 'six'`, next time it warns about missing module 'appdirs'. Any hint about what I have to do to solve this?

**Comment by rennerocha** [comment]
I vaguely remember to have problems installing `chompjs` in a certain Python version. What is the exact Python version are you using?

**Comment by gsusin** [comment]
```
(.venv) susin@bemtevi:~/code/querido-diario> python -V
Python 3.6.12
```

**Comment by gsusin** [comment]
Upgraded to Python 3.8.6 and `chompjs` was installed correctly. After complete installation from `requirements.txt`, I had to add one missing module manually:
`pip install requests`
Now I can run any spider with `scrapy`! Thank you @rennerocha!
