### ISSUE TITLE
Fix TypeError in Campo Grande-MS spider

### ISSUE THREAD

**Issue by rennerocha** [okfn-brasil/querido-diario#574]
Spider is working and data is being collected. However we have a TypeError that is happening in every spider execution:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/[defer.py](http://defer.py/)", line 132, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/[python.py](http://python.py/)", line 354, in __next__
    return next([self.data](http://self.data/))
  File "/usr/local/lib/python3.10/site-packages/scrapy/utils/[python.py](http://python.py/)", line 354, in __next__
    return next([self.data](http://self.data/))
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.10/site-packages/sh_scrapy/[middlewares.py](http://middlewares.py/)", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.10/site-packages/scrapy/spidermiddlewares/[offsite.py](http://offsite.py/)", line 29, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.10/site-packages/scrapy/spidermiddlewares/[referer.py](http://referer.py/)", line 342, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.10/site-packages/scrapy/spidermiddlewares/[urllength.py](http://urllength.py/)", line 40, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/usr/local/lib/python3.10/site-packages/scrapy/spidermiddlewares/[depth.py](http://depth.py/)", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.10/site-packages/scrapy/core/[spidermw.py](http://spidermw.py/)", line 66, in _evaluate_iterable
    for r in iterable:
  File "/app/__main__.egg/gazette/spiders/ms_campo_grande.py", line 25, in parse
    for entry in response.json()["data"]:
TypeError: 'bool' object is not iterable
```

Production logs for reference:
[log_ms_campo_grande_626.txt](https://github.com/okfn-brasil/querido-diario/files/8984970/log_ms_campo_grande_626.txt)

**Comment by wesleyolvr** [comment]
#577

**Comment by wesleyolvr** [comment]
#577 if the value is false, returns empty list

**Comment by rennerocha** [comment]
Fixed by https://github.com/okfn-brasil/querido-diario/pull/576 and https://github.com/okfn-brasil/querido-diario/pull/580
