### ISSUE TITLE
Upgrade de `spidermon` para pelo menos versão 1.17.0

### ISSUE THREAD

**Issue by ayharano** [okfn-brasil/querido-diario#647]
Olá.

Eu contribui para esse repositório em algum momento no passado e pretendo abrir alguns PRs para o próximo mês.

Eu ajustei meu ambiente local para poder trabalhar no código novo e o commit mais recente local da branch `main` é 6e80f285666f3f33270d25ac16143e10e4da6030.

Uso Fedora Linux e instalei a versão mais recente do Python 3.9 via pyenv (3.9.14) para pode trabalhar.

Segui as instruções do README para instalação.

Quando rodei o comando para coletar de um spider específico localmente, avisou sobre a falta de um módulo específico.

```python
$ scrapy crawl es_vila_velha
2022-09-27 20:42:25 [scrapy.utils.log] INFO: Scrapy 2.6.2 started (bot: gazette)
2022-09-27 20:42:25 [scrapy.utils.log] INFO: Versions: lxml 4.9.1.0, libxml2 2.9.14, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 22.4.0, Python 3.9.14 (main, Sep 27 2022, 20:27:11) - [GCC 12.2.1 20220819 (Red Hat 12.2.1-2)], pyOpenSSL 22.0.0 (OpenSSL 3.0.3 3 May 2022), cryptography 37.0.2, Platform Linux-5.19.9-200.fc36.x86_64-x86_64-with-glibc2.35
2022-09-27 20:42:25 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'gazette',
 'DOWNLOAD_TIMEOUT': 360,
 'EDITOR': '/usr/bin/nano',
 'FILES_STORE_S3_ACL': 'public-read',
 'NEWSPIDER_MODULE': 'gazette.spiders',
 'SPIDER_MODULES': ['gazette.spiders']}
2022-09-27 20:42:25 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
2022-09-27 20:42:25 [scrapy.extensions.telnet] INFO: Telnet Password: ------
Traceback (most recent call last):
  File "/home/user/querido-diario/venv/bin/scrapy", line 8, in <module>
    sys.exit(execute())
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/cmdline.py", line 154, in execute
    _run_print_help(parser, _run_command, cmd, args, opts)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/cmdline.py", line 109, in _run_print_help
    func(*a, **kw)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/cmdline.py", line 162, in _run_command
    cmd.run(args, opts)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/commands/crawl.py", line 22, in run
    crawl_defer = self.crawler_process.crawl(spname, **opts.spargs)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/crawler.py", line 204, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/crawler.py", line 237, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/crawler.py", line 315, in _create_crawler
    return Crawler(spidercls, self.settings, init_reactor=init_reactor)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/crawler.py", line 86, in __init__
    self.extensions = ExtensionManager.from_crawler(self)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/middleware.py", line 59, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/middleware.py", line 41, in from_settings
    mw = create_instance(mwcls, settings, crawler)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/utils/misc.py", line 166, in create_instance
    instance = objcls.from_crawler(crawler, *args, **kwargs)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/spidermon/contrib/scrapy/extensions.py", line 81, in from_crawler
    ext = cls(
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/spidermon/contrib/scrapy/extensions.py", line 39, in __init__
    self.spider_closed_suites = [
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/spidermon/contrib/scrapy/extensions.py", line 40, in <listcomp>
    self.load_suite(s) for s in spider_closed_suites or []
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/spidermon/contrib/scrapy/extensions.py", line 62, in load_suite
    raise e  # TO-DO
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/spidermon/contrib/scrapy/extensions.py", line 60, in load_suite
    suite_class = load_object(suite_to_load)
  File "/home/user/querido-diario/venv/lib/python3.9/site-packages/scrapy/utils/misc.py", line 61, in load_object
    mod = import_module(module)
  File "/home/user/.pyenv/versions/3.9.14/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/user/querido-diario/data_collection/gazette/monitors.py", line 4, in <module>
    from spidermon.contrib.actions.discord import SendDiscordMessage
ModuleNotFoundError: No module named 'spidermon.contrib.actions.discord'
```

Então estou abrindo essa issue para verificar alguns pontos.

1. no README não consta se é para usar versão específica de Python, apesar do [`requirements.txt` apontar que as dependências estão preparadas para o uso do Python 3.10](https://github.com/okfn-brasil/querido-diario/blob/6e80f285666f3f33270d25ac16143e10e4da6030/data_collection/requirements.txt#L2). Tem alguma versão específica de Python que é melhor recomendado para o desenvolvimento?
2. seria o caso de ter alguma diretiva para não efetuar o import de [`spidermon.contrib.actions.discord.SendDiscordMessage`](https://github.com/okfn-brasil/querido-diario/blob/6e80f285666f3f33270d25ac16143e10e4da6030/data_collection/gazette/monitors.py#L4) para o desenvolvimento local, já que provavelmente não seria o caso de enviar mensagem para o Discord no uso de spiders locais?
3. teria alguma instrução de configuração pendente no README?

PS: reconfigurei meu ambiente local para usar o Python 3.10.7 e o erro de import é o mesmo que originalmente descrito.

PS2: vi pelo changelog de `spidermon` que [o contrib de discord entrou na versão 1.17.0](https://spidermon.readthedocs.io/en/latest/changelog.html#id1) mas ao instalar com `python -m  pip install -r data_collection/requirements-dev.txt`, a versão instalada foi 1.16.2:

```shell
$ pip freeze | grep spidermon
spidermon==1.16.2
```

PS3: trocando localmente a linha de `spidermon` de `requirements-dev.txt` para `spidermon[monitoring]==1.17` funcionou. Com base em commits anteriores, vi que tem algum procedimento via arquivos .in para regerar os requirements*.txt.

**Comment by trevineju** [comment]
@rennerocha você poderia dar uma olhada? 
se precisar atualizar o README, aproveita e já me diz ou adiciona lá no (#643), já que estou trabalhando nos READMEs dos repositórios do QD.

**Comment by ayharano** [comment]
Eu reinstalei o projeto em outra máquina e encontrei a causa da issue:

`requirements.txt` está configurado para usar `spidermon` com a versão 1.17.0 [como podemos validar nessa linha específica de `requirements.txt`](https://github.com/okfn-brasil/querido-diario/blob/d04b95ce933fadb4e300d1219cb168ce7f8b9f30/data_collection/requirements.txt#L208).

Porém, como o README indica para instalarmos usando `requirements-dev.txt` e lá [está pinando `spidermon` para a versão 1.16.2](https://github.com/okfn-brasil/querido-diario/blob/d04b95ce933fadb4e300d1219cb168ce7f8b9f30/data_collection/requirements-dev.txt#L244).

Não conheço qual ferramenta calcula os `*.txt` a partir de `*.in`, mas parece ser o caso de regerar a partir de `requirements-dev.in`.

**Comment by giuliocc** [comment]
@ayharano muito obrigado por encontrar o problema!

A ferramenta utilizada é a [`pip-tools`](https://pypi.org/project/pip-tools/). Como `pip-compile requirements.in > requirements.txt` e  `pip-compile requirements-dev.in > requirements-dev.txt` você conseguiria gerar os arquivos `.txt` (com a árvore de dependência fixada) a partir das restrições especificadas nos `.in`.

Poderia tentar aí e abrir um PR?

**Comment by ayharano** [comment]
Olá @giuliocc.

Conforme solicitado, regerei os arquivos `requirements*.txt` a partir dos respectivos `requirements*.in` no PR #709.

Zerei meu venv de Python 3.10.7, instalei só o `pip-compile`, fiz o procedimento indicado, instalei de `requirements-dev.txt` e rodei um scrawler de maneira bem sucedida.
